packages:
  - '.'

allowBuilds:
  unrs-resolver: set this to true or false
  vue-demi: set this to true or false

minimumReleaseAgeExclude:
  - '@lucide/vue@1.31.0'

publicHoistPattern:
  - '@inertiajs/core'
